Lesson 20: Redux saga
mkremnev/app-calc pull request #16
Opened 2020-09-26 15:00 UTC by mkremnev

2020-09-26 15:50 UTC, nickovchinnikov commented on src/sagas/saga.tsx
> +export function* helloSaga() {
Тестовый код

2020-09-26 15:50 UTC, nickovchinnikov commented on src/rdx/reducer/index.ts
> +export { fieldReducers } from './field';
Можете уже начинать использовать ducks, потом будет намного сложнее

2020-09-26 15:52 UTC, nickovchinnikov commented on src/modules/Login/reducer.ts
> +export const { reducer, actions } = LoginSlice;
Вы можете использовать эти переменные, вместо вызова `LoginSlice.reducer` -> src/store.ts

2020-09-26 15:53 UTC, nickovchinnikov commented on src/modules/Login/reducer.ts
> +import { createSlice, PayloadAction } from '@reduxjs/toolkit';
А где тесты?

2020-09-26 15:54 UTC, nickovchinnikov commented on src/modules/Login/saga.ts
> +import { login, logout, getUserSession } from '@/api/auth';
Не вижу теста

2020-09-26 15:54 UTC, nickovchinnikov commented on src/store.ts
> +		...getDefaultMiddleware({
Время убрать другие middlewares, имхо

2020-09-26 15:55 UTC, nickovchinnikov commented on src/components/View/Navigation.tsx
> +	& > li h4 {
Создавайте разные компоненты и композируйте их, это сила

2020-09-26 15:56 UTC, nickovchinnikov requested changes
Отписал замечания, надеюсь поможет! Есть над чем поработать!

2020-09-27 02:49 UTC, mkremnev commented on src/rdx/reducer/index.ts
> +export { fieldReducers } from './field';
Принял, спасибо, как раз начинаю переделывать и вникать.

2020-09-27 02:49 UTC, mkremnev commented on src/modules/Login/reducer.ts
> +export const { reducer, actions } = LoginSlice;
Точно, спасибо.

2020-09-27 02:50 UTC, mkremnev commented on src/modules/Login/reducer.ts
> +import { createSlice, PayloadAction } from '@reduxjs/toolkit';
Согласен, не доделал.

2020-09-27 02:50 UTC, mkremnev commented on src/modules/Login/saga.ts
> +import { login, logout, getUserSession } from '@/api/auth';
И здесь, приступил писать.

2020-09-27 02:51 UTC, mkremnev commented on src/store.ts
> +		...getDefaultMiddleware({
Это временное решение на ошибку сериализации данных. Если убрать то в консоли, красным все забивается.

2020-09-27 02:52 UTC, mkremnev commented on src/components/View/Navigation.tsx
> +	& > li h4 {
Принял, с композицией еще страдаю, надо тренироваться.

2020-09-27 03:10 UTC, mkremnev commented
> Тестовый код 

Точно, забыл убрать.

2020-10-08 12:01 UTC, nickovchinnikov commented on src/components/View/Navigation.tsx
> +	& > li h4 {
почему бы не начать делать это сразу?)

2020-10-08 15:36 UTC, mkremnev commented on src/components/View/Navigation.tsx
> +	& > li h4 {
Согласен, нужно было сразу делать)

2020-10-09 20:31 UTC, merged